/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.bean.Limite_digitos;
import model.bean.moto;
import model.bean.motoClub;
import model.bean.pessoa;
import model.bean.usuario;
import model.dao.mcDAO;
import model.dao.pessoaDAO;
import model.dao.usuarioDAO;

/**
 *
 * @author papiro
 */
public class TelaLogin extends javax.swing.JFrame {
    private usuarioDAO form;
    private pessoaDAO form1;
    private mcDAO form2;
    private usuario form3;
    private pessoa form4;
    private motoClub form5;
    private String usuario;
    private String senha;
    private List<usuario> usuarios;
    private List<pessoa> pessoas;
    private List<motoClub> MCs;
    private List<moto> motos;
    
    /**
     * Creates new form telaInicial
     */
    public TelaLogin() {
        initComponents();
        form = new usuarioDAO();
        form1 = new pessoaDAO();
        form2 = new mcDAO();
        form3 = new usuario();
        form4 = new pessoa();
        form5 = new motoClub();
        txtSenha.setDocument(new Limite_digitos(12));
        usuario = "";
        senha = "";
        usuarios = form.Validar();
        pessoas = form1.Validar();
        MCs = form2.Validar();
        motos = form2.buscaMotos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        checkMostrar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 128, 0));
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Usuário");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Senha");

        btnLogin.setBackground(new java.awt.Color(1, 1, 1));
        btnLogin.setForeground(new java.awt.Color(254, 254, 254));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/motologoharleypng.png"))); // NOI18N

        lblCadastrar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCadastrar.setText("Cadastre-se");
        lblCadastrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseDragged(evt);
            }
        });
        lblCadastrar.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblCadastrarMouseWheelMoved(evt);
            }
        });
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseClicked(evt);
            }
        });

        checkMostrar.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        checkMostrar.setText("Mostrar");
        checkMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkMostrar))
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCadastrar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(lblCadastrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseClicked
        // TODO add your handling code here:
        TelaCadastroPessoa tela = new TelaCadastroPessoa();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCadastrarMouseClicked

    private void lblCadastrarMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblCadastrarMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCadastrarMouseWheelMoved

    private void lblCadastrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCadastrarMouseDragged

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(txtUsuario.getText().trim().equals("") || txtSenha.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"CAMPOS OBRIGATÓRIOS!");
        }
        else{
            usuario = txtUsuario.getText();
            senha = txtSenha.getText();
            boolean cont = false;
            boolean cont1 = false;
            
            for(pessoa p:form.ValidarP()){
                for(usuario u:form.Validar()){    
                    if(p.getId() == u.getIdpessoa()){
                        if(u.getNome().equals(usuario)){
                            cont1 = true;
                            if(u.getSenha().equals(senha)){
                                cont = true;
                                form3 = u;
                                form4 = p;
                                for(motoClub mc:form.ValidarMC(u)){
                                    if(u.getIdmc() == mc.getId())
                                        form5 = mc;
                                }
                                break;                
                            }
                        }
                    }
                }
            }
            if(cont == true && cont1 == true){
                JOptionPane.showMessageDialog(null,"LOGADO COM SUCESSO!");
                TelaMenuInicial menu = new TelaMenuInicial();
                menu.getObjetos(usuarios,pessoas,MCs,motos);
                menu.getUsuario(form3);
                menu.getPessoa(form4);
                menu.getMc(form5);
                menu.carregarIntegrantes();
                menu.setVisible(true);
                dispose();
            }else if(cont1 != true){
                JOptionPane.showMessageDialog(null,"USUÁRIO INVÁLIDO!CASO NÃO POSSUA CADASTRO REALIZE CLICANDO SOBRE O LINK ABAIXO.");
            }else if(cont != true)
                JOptionPane.showMessageDialog(null,"SENHA INVÁLIDA!CASO NÃO POSSUA CADASTRO REALIZE CLICANDO SOBRE O LINK ABAIXO.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void checkMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMostrarActionPerformed
        // TODO add your handling code here:
        txtSenha.setEchoChar((char)0);
        if(checkMostrar.isSelected()==false)
        txtSenha.setEchoChar('*');
    }//GEN-LAST:event_checkMostrarActionPerformed

    public void getPessoa(pessoa p){form4 = p;}
    public void getUsuario(usuario u){form3 = u;}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox checkMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
