/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.moto;
import model.bean.motoClub;
import model.bean.pessoa;
import model.bean.usuario;
import model.dao.mcDAO;
import model.dao.pessoaDAO;
import model.dao.usuarioDAO;

/**
 *
 * @author papiro
 */
public class TelaPesquisaMC extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesquisaMC
     */
    private List<usuario> usuarios;
    private List<motoClub> MCs;
    private List<pessoa> pessoas;
    private List<moto> motos1;
    private usuarioDAO form;
    private pessoaDAO form1;
    private mcDAO form2;
    private moto moto;
    private pessoa pessoa;
    private usuario usuario;
    private motoClub mc;
    
    public TelaPesquisaMC() {
        initComponents();
        form = new usuarioDAO();
        form1 = new pessoaDAO();
        form2 = new mcDAO();
        mc = new motoClub();
        DefaultTableModel modelo = (DefaultTableModel) tableMCs.getModel();
        tableMCs.setRowSorter(new TableRowSorter(modelo));
        
        LerTabela(mc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblRegiao = new javax.swing.JLabel();
        lblQtd = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMCs = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemHome4 = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        editarMC = new javax.swing.JMenuItem();
        editarUsuario = new javax.swing.JMenuItem();
        excluirUsuario = new javax.swing.JMenuItem();
        excluirMC = new javax.swing.JMenuItem();
        menuListar = new javax.swing.JMenu();
        motos = new javax.swing.JMenuItem();
        motoclubs = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painel.setBackground(new java.awt.Color(255, 128, 0));
        painel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MotoClubs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Resultado da pesquisa:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Região:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Estado:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Quantidade:");

        tableMCs.setAutoCreateRowSorter(true);
        tableMCs.setBackground(new java.awt.Color(1, 1, 1));
        tableMCs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 1, true));
        tableMCs.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        tableMCs.setForeground(new java.awt.Color(254, 254, 254));
        tableMCs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "    INTEGRANTES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMCs.setAutoscrolls(false);
        tableMCs.setColumnSelectionAllowed(false);
        tableMCs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableMCs.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tableMCs.setFocusable(false);
        tableMCs.setGridColor(new java.awt.Color(254, 254, 254));
        tableMCs.setPreferredSize(new java.awt.Dimension(225, 175));
        tableMCs.setSelectionForeground(new java.awt.Color(1, 1, 1));
        jScrollPane1.setViewportView(tableMCs);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(painelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(20, 20, 20)
                                        .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        menuBar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuBar.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        menuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page.png"))); // NOI18N
        menuArquivo.setText("Arquivo");

        itemHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        itemHome4.setText("Home");
        itemHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHome4ActionPerformed(evt);
            }
        });
        menuArquivo.add(itemHome4);

        itemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_out.png"))); // NOI18N
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemSair);

        menuBar.add(menuArquivo);

        menuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        menuEditar.setText("Editar");

        editarMC.setBackground(new java.awt.Color(1, 1, 1));
        editarMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconMoto.png"))); // NOI18N
        editarMC.setText("MotoClub");
        editarMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMCActionPerformed(evt);
            }
        });
        menuEditar.add(editarMC);

        editarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_edit.png"))); // NOI18N
        editarUsuario.setText("Info. Pessoais");
        editarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioActionPerformed(evt);
            }
        });
        menuEditar.add(editarUsuario);

        excluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_delete.png"))); // NOI18N
        excluirUsuario.setText("Excluir Usuário");
        excluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUsuarioActionPerformed(evt);
            }
        });
        menuEditar.add(excluirUsuario);

        excluirMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_delete.png"))); // NOI18N
        excluirMC.setText("ExcluirMC");
        excluirMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirMCActionPerformed(evt);
            }
        });
        menuEditar.add(excluirMC);

        menuBar.add(menuEditar);

        menuListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/printer.png"))); // NOI18N
        menuListar.setText("Listar");

        motos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/moto.png"))); // NOI18N
        motos.setText("Motos");
        motos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motosActionPerformed(evt);
            }
        });
        menuListar.add(motos);

        motoclubs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group.png"))); // NOI18N
        motoclubs.setText("MotoClubs");
        motoclubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoclubsActionPerformed(evt);
            }
        });
        menuListar.add(motoclubs);

        menuBar.add(menuListar);

        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/help.png"))); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        menuBar.add(menuSobre);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void LerTabela(motoClub mc){
        DefaultTableModel modelo = (DefaultTableModel) tableMCs.getModel();
            modelo.setNumRows(0);
            for(pessoa p:form.ValidarMcP(mc)){
                modelo.addRow(new Object[]{
                   p.getNome(),
                });
            }
    }
    
    private void itemHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHome4ActionPerformed
        // TODO add your handling code here:
        TelaMenuInicial tela = new TelaMenuInicial();
        tela.getObjetos(usuarios, pessoas, MCs, motos1);
        tela.getMc(mc);
        tela.getPessoa(pessoa);
        tela.getUsuario(usuario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemHome4ActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // TODO add your handling code here:
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    private void editarMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMCActionPerformed
        // TODO add your handling code here:
        TelaEditarMC tela = new TelaEditarMC();
        tela.getObjetos(usuarios, pessoas, MCs, motos1);
        tela.getMc(mc);
        tela.getPessoa(pessoa);
        tela.getUsuario(usuario);
        tela.inserir();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarMCActionPerformed

    private void editarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuarioActionPerformed
        // TODO add your handling code here:
        TelaEditarPessoa tela = new TelaEditarPessoa();
        tela.getObjetos(usuarios, pessoas, MCs, motos1);
        tela.getMc(mc);
        tela.getPessoa(pessoa);
        tela.getUsuario(usuario);
        tela.inserir();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarUsuarioActionPerformed

    private void excluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirUsuarioActionPerformed
        // TODO add your handling code here:
        PopUpConfirmar conf = new PopUpConfirmar();
        conf.confirmar("usuario",usuario,mc,pessoa,MCs); //FALTA CRIAR UMA RELACAO ENTRE USUARIO, PESSOA LA NO BD COM A FOREIGN KEY
        conf.setVisible(true);
    }//GEN-LAST:event_excluirUsuarioActionPerformed

    private void excluirMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirMCActionPerformed
        // TODO add your handling code here:
        PopUpConfirmar conf = new PopUpConfirmar();
        conf.confirmar("mc",usuario,mc,pessoa,MCs); //FALTA CRIAR UMA RELACAO ENTRE USUARIO E MC LA NO BD COM A FOREIGN KEY
        conf.setVisible(true);
    }//GEN-LAST:event_excluirMCActionPerformed

    private void motosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motosActionPerformed
        // TODO add your handling code here:
        TelaMotos tela1 = new TelaMotos();
        tela1.setVisible(true);
        tela1.getObjetos(usuarios, pessoas, MCs, motos1);
        tela1.getMc(mc);
        tela1.getPessoa(pessoa);
        tela1.getUsuario(usuario);
        tela1.inserir();
        dispose();
    }//GEN-LAST:event_motosActionPerformed

    private void motoclubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoclubsActionPerformed
        // TODO add your handling code here:
        TelaMCs tela1 = new TelaMCs();
        tela1.getObjetos(usuarios, pessoas, MCs, motos1);
        tela1.getMc(mc);
        tela1.getPessoa(pessoa);
        tela1.getUsuario(usuario);
        tela1.setVisible(true);
        dispose();
    }//GEN-LAST:event_motoclubsActionPerformed

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Sistema de gerenciamento de MotorClubs\nVersão 1.0");
    }//GEN-LAST:event_menuSobreMouseClicked

    public void pesquisa(){
       
        lblNome.setText(mc.getNome());
        lblRegiao.setText(mc.getRegiao());
        lblEstado.setText(mc.getEstado());
        lblQtd.setText(Integer.toString(mc.getQtd()));
        
        LerTabela(mc);
    }
    
    public void getObjetos(List<usuario> u, List<pessoa> p, List<motoClub> mc, List<moto> m){
        usuarios = u;
        MCs = mc; 
        pessoas = p;
        motos1 = m;
    }
    public void getMc(motoClub mc){this.mc = mc;}
    public void getPessoa(pessoa p){pessoa = p;}
    public void getUsuario(usuario u){usuario = u;}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisaMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editarMC;
    private javax.swing.JMenuItem editarUsuario;
    private javax.swing.JMenuItem excluirMC;
    private javax.swing.JMenuItem excluirUsuario;
    private javax.swing.JMenuItem itemHome4;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblRegiao;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuListar;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuItem motoclubs;
    private javax.swing.JMenuItem motos;
    private javax.swing.JPanel painel;
    private javax.swing.JTable tableMCs;
    // End of variables declaration//GEN-END:variables
}
