/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.bean.motoClub;
import model.bean.pessoa;
import model.bean.usuario;
import model.bean.validacoes;
import model.dao.mcDAO;
import model.dao.pessoaDAO;
import model.dao.usuarioDAO;

/**
 *
 * @author papiro
 */
public class AlterarPessoa extends javax.swing.JFrame {

    /**
     * Creates new form AlterarPessoa
     */
    private List<usuario> usuarios;
    private List<pessoa> pessoas;
    private List<motoClub> motoClubs;
    private usuarioDAO form;
    private pessoaDAO form1;
    private mcDAO form2;
    private pessoa pessoa;
    private usuario usuario;
    private motoClub mc;
    private validacoes aux;
    
    public AlterarPessoa() {
        initComponents();
        grupoBotoes();
        form = new usuarioDAO();
        form1 = new pessoaDAO();
        form2 = new mcDAO();
        pessoa = new pessoa();
        usuario = new usuario();
        aux = new validacoes();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkNome = new javax.swing.JRadioButton();
        checkCpf = new javax.swing.JRadioButton();
        checkData = new javax.swing.JRadioButton();
        checkMC = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtCampo = new javax.swing.JTextField();
        btnConfimar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 128, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Pessoa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Selecione qual informação deseja alterar:");

        checkNome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        checkNome.setText("Nome");

        checkCpf.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        checkCpf.setText("Cpf");

        checkData.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        checkData.setText("Data de Nascimento");

        checkMC.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        checkMC.setText("MotoClub");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Informe novo:");

        btnConfimar.setBackground(new java.awt.Color(1, 1, 1));
        btnConfimar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnConfimar.setForeground(new java.awt.Color(254, 254, 254));
        btnConfimar.setText("Confirmar");
        btnConfimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfimarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(1, 1, 1));
        btnVoltar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(254, 254, 254));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkNome)
                            .addComponent(checkCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkData)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkMC)
                                .addGap(42, 42, 42)))
                        .addGap(39, 39, 39))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2)
                    .addComponent(btnConfimar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkNome)
                    .addComponent(checkData))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMC)
                    .addComponent(checkCpf))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfimar)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfimarActionPerformed
        // TODO add your handling code here:
        if(checkNome.isSelected() == true){
                pessoa.setNome(txtCampo.getText());
                if(form1.Alterar(pessoa, checkNome.getText())){
                    JOptionPane.showMessageDialog(null,"Alterado com sucesso!");
                    dispose();
                }else
                    JOptionPane.showMessageDialog(null, "Erro ao alterar! Informação incorreta.");
        }else if(checkCpf.isSelected() == true){
             
                if(txtCampo.getText().length()<=11){
                    pessoa.setCpf(aux.CpfConvertido(txtCampo.getText()));            
                }else if(txtCampo.getText().length()==14)
                    pessoa.setCpf(txtCampo.getText());
                else
                     JOptionPane.showMessageDialog(null,"CPF INVÁLIDO");
            if(form1.Alterar(pessoa, checkCpf.getText())){
                JOptionPane.showMessageDialog(null,"Alterado com sucesso!");
                dispose();
            }else
                JOptionPane.showMessageDialog(null, "Erro ao alterar! Informação incorreta.");
        }else if(checkData.isSelected() == true){
               if(txtCampo.getText().length()<=8){
                   // String data = aux.dataBrasil(txtCampo.getText());
                    pessoa.setData(aux.dataBD(txtCampo.getText()));

                }
                else{
                    pessoa.setData(aux.dataBD(txtCampo.getText()));
                }
            if(form1.Alterar(pessoa, checkData.getText())){
               JOptionPane.showMessageDialog(null,"Alterado com sucesso!");
               dispose();
           }else
               JOptionPane.showMessageDialog(null, "Erro ao alterar! Informação incorreta.");
        }else if(checkMC.isSelected() == true){
            String campo = txtCampo.getText();
            campo = campo.substring(0,1).toUpperCase()+campo.substring(1);
            boolean cont = false;
            for(motoClub mc:form2.Validar()){
                if(mc.getNome().indexOf(campo) != -1){
                    removerIntegrantes(usuario);
                    pessoa.setMc(mc.getNome()+"-"+mc.getEstado());
                    usuario.setIdmc(mc.getId());
                    this.mc = mc;
                    cont = true;
                    break;
                }
            }   
            if(cont){
                if(form1.Alterar(pessoa, checkMC.getText())){
                   if(form.Alterar(usuario,checkMC.getText())){
                        JOptionPane.showMessageDialog(null,"Alterado com sucesso!");
                        adicionarNovo(usuario);
                        dispose();
                   }else
                        JOptionPane.showMessageDialog(null, "Erro ao alterar! Informação incorreta.");
                }else
                        JOptionPane.showMessageDialog(null, "Erro ao alterar! Informação incorreta.");
            }else
                JOptionPane.showMessageDialog(null,"MOTOCLUB NÃO CADASTRADO, CASO QUEIRA CADASTRAR O SEU MC VÁ AO MENU INICIAL E CLIQUE NO LINL CADASTRAR.");
        }else
            JOptionPane.showMessageDialog(null,"Selecione uma Opção.");
    }//GEN-LAST:event_btnConfimarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    public void grupoBotoes(){
        ButtonGroup gb = new ButtonGroup();
        gb.add(checkMC);
        gb.add(checkNome);
        gb.add(checkCpf);
        gb.add(checkData);
    }
    public void getObjetos(List<usuario> u, List<pessoa> p, List<motoClub> mc){
        usuarios = u;
        pessoas = p;
        motoClubs = mc;
    }
    public void getPessoa(pessoa p){pessoa = p;}
    public void getUsuario(usuario u){usuario = u;}
    public void removerIntegrantes(usuario u){
        System.out.println(u.getIdmc());
        for(motoClub mc:motoClubs){
            if(u.getIdmc() == mc.getId()){
                mc.setIntegrantes(mc.getIntegrantes()-1);
                form2.CadastrarIntegrante(mc);
            }
            System.out.println("nome: "+mc.getNome()+" int: "+mc.getIntegrantes());
        }
    }
    public void adicionarNovo(usuario u){
        System.out.println(u.getIdmc());
        for(motoClub mc:motoClubs){
            if(u.getIdmc() == mc.getId()){
                mc.setIntegrantes(mc.getIntegrantes()+1);
                form2.CadastrarIntegrante(mc);
            }
            System.out.println("nome: "+mc.getNome()+" int: "+mc.getIntegrantes());
        }
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfimar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JRadioButton checkCpf;
    private javax.swing.JRadioButton checkData;
    private javax.swing.JRadioButton checkMC;
    private javax.swing.JRadioButton checkNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCampo;
    // End of variables declaration//GEN-END:variables
}
